["gcp_service_account"]
type = "service_account"
project_id = "register-2025-469911"
private_key_id = "9e9b1605c50d01d4d0e305589eadbea3622473d8"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8MYf/SW91Vda6
+w1aInruSdrzugRipMH9geiSR+DkNVhEKT8o3rbDu/VL3uSA739Qs7DbWoEMd+2E
zLgiJBPGCzM6s75OFQF4XBaplVva43R8TgrBQ66aqgVsJ1sVn8lsivr02gsKPyos
8Ye+/wrYov2ZkT9ag1RMo4Tc9nyKTSBXGDzZu2HST2qd7SNgMFFMjFlPUvYzrCJl
hNalRF8mbArVs63maN/Vd3ij1hKIVBtsn88RIgIOMHB7bxd3NVUZdEJGTYR6hyvZ
0OiWxgKjdn0T2lAkcyfbUBRX4DX/9cAPL+UmCPTccNOBWJSBi3tiUtUk9gLLqZ2P
cMa+kxR1AgMBAAECggEADChAT9aPnmCC3vte28bEcuZPKwAw+P+0ZHW4RNLjN/rW
OTkCPS1TWIZTjKjZJsHR/gWi/tie445PyAzC4bm7k/H0nO3a9QetsPfJ+FSPZYQy
FIxPbOK8FykKm/etjlJkhwrctrqV4f3onJSnH0iHNoLOUoBWkQ37gSPtw6nMq9ET
7/wFb/Jy7cbcZUgAa8iazARNoOz6njEbdaUQPzj6wjTqNyRF6zoXSNEANc/g2bNZ
pTAA00CCALLCpydz4+UVB3AjO1onTiIEbl38jkeo7o1Jockteu4XWIFYIRhmd/we
PApBDoDAsttH34TDRoqCJY2nB3c5D6V9FPQ5JjB9QQKBgQDo+YM2BoA81hK2HtnK
6TeiKHKcPh46AdvU1/+/L2oga2aWEmzRYGCcxan/qp5nIdrGpYTdmXRlbvGHtNvB
xywJ+LZZxoGU4gEI95n7AOgaLUuu0dModEDcR6G2mAtGNLkbDkQh7abo4ETZG1WH
lZQMrLAdfKbl6N7M2xAhJh4DBQKBgQDOywLPepzJgRPCDX5FOpUzKjOj4O+rF5Ey
HZAFzoEtYp39k9xaoQARYg/N0iuOXGdulcjtmi9hVMON240qEcYeVIhLF6Xh1QhZ
e52v/jiTnNVF60Sx7lfEvPqogEneA2Vi8XO1TqWJZgL6KzLpuzj1PxIVdLHYSHxd
YtlA5FNmsQKBgBnzUQ4/gyFDpynqHdBgUfYaE0ocETnc4yO+O5qMKYIa9H5a5wwb
dCeCTQFRe/t45eminj4gzbpOtVCscJ4RFXK25Xjyh5SR6BOboOc4nqHr0bZTYPXs
nRzsTbMNFJRpYwUEfcpZsnHWKVUVml1T5/3RbnyaWezaF5cx/4XxvP4RAoGBAJEo
yIxEEZMRXIE3X4/RE7KayS0cVKDRJkb7oYGx99OYCjdad6/WnGmXYGimQ5TnIGPs
GONQ/DlievM1Tt5dI6lexV2Q+AySsg2+TG6iEazsxnkSMWKFYG7mCT4G79M8pwrR
WtvGnUTZqvVZJaAUoGLnJxaQl9au6z3SiZaXsEPBAoGBALm2Ub5PqqDLFk5rR2Vp
1T6Q247UeJd1vVG+08Nr8KUTsesNsBAjQOfJCdnmOXokpd5jIaaDnJ3uzfMqPHOw
k8VyJzTQO8zhFtlx26oIYTjEiFYz+Exj3/1PU7uqymt7VQfWzUS360e5gcbAc+3+
M3ZapDPj/4R4Noi2BcEp/0Rh
-----END PRIVATE KEY-----"""
client_email = "register-914@register-2025-469911.iam.gserviceaccount.com"
client_id = "116938814914255140439"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/register-914%40register-2025-469911.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
